AppBundle\Entity\Advisor:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AdvisorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        memberID:
            type: integer
        post:
            type: string
            length: '50'
            nullable: true
        year:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
