AppBundle\Entity\Committee:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommitteeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        memberID:
            type: integer
            unique: true
        post:
            type: string
            length: '20'
        year:
            type: date
    lifecycleCallbacks: {  }
