AppBundle\Entity\Exhibition:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ExhibitionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: string
            length: '20'
            unique: true
        theme:
            type: string
            length: '30'
        locationMap:
            type: string
            length: '30'
            column: location_map
    lifecycleCallbacks: {  }
