AppBundle\Entity\Meeting:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MeetingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datetime:
            type: datetime
        venue:
            type: string
            length: '30'
        agenda:
            type: text
        minute:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
