AppBundle\Entity\Transaction:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TransactionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datetime:
            type: datetime
        billNumber:
            type: string
            length: '10'
            unique: true
            column: bill_number
        institutionID:
            type: integer
            nullable: true
        eventID:
            type: integer
            nullable: true
        amount:
            type: decimal
            precision: '9'
            scale: '2'
        receiverID:
            type: integer
        remarks:
            type: string
            length: '30'
            nullable: true
        direction:
            type: string
            length: '3'
    lifecycleCallbacks: {  }
